# Generated by Django 3.2.25 on 2025-03-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('werknemers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Werknemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('functie', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
