# Generated by Django 5.1.7 on 2025-04-11 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boekhouding_grootboekrekeningen', '0001_initial'),
        ('werknemers', '0002_werknemer'),
    ]

    operations = [
        migrations.AddField(
            model_name='werknemer',
            name='actief',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='werknemer',
            name='grootboekrekening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boekhouding_grootboekrekeningen.grootboekrekening', verbose_name='Kostenrekening'),
        ),
        migrations.AddField(
            model_name='werknemer',
            name='uurloon',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8),
            preserve_default=False,
        ),
    ]
