# Generated by Django 5.1.7 on 2025-04-11 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boekhouding_grootboekrekeningen', '0001_initial'),
        ('werknemers', '0003_werknemer_actief_werknemer_grootboekrekening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='werknemer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='werknemer',
            name='grootboekrekening',
        ),
        migrations.RemoveField(
            model_name='werknemer',
            name='naam',
        ),
        migrations.RemoveField(
            model_name='werknemer',
            name='telefoonnummer',
        ),
        migrations.AddField(
            model_name='werknemer',
            name='achternaam',
            field=models.CharField(default='onbekend', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='werknemer',
            name='geboortedatum',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='werknemer',
            name='loonrekening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werknemers', to='boekhouding_grootboekrekeningen.grootboekrekening', verbose_name='Loon Grootboekrekening'),
        ),
        migrations.AddField(
            model_name='werknemer',
            name='voornaam',
            field=models.CharField(default='onbekend', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='werknemer',
            name='functie',
            field=models.CharField(blank=True, default='onbekend', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='werknemer',
            name='uurloon',
            field=models.DecimalField(decimal_places=2, help_text='Bruto uurloon in euro’s', max_digits=6),
        ),
    ]
