# Generated by Django 3.2.25 on 2025-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('startdatum', models.DateField()),
                ('einddatum', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('omschrijving', models.TextField(blank=True)),
                ('actief', models.BooleanField(default=True)),
            ],
        ),
    ]
