# Generated by Django 3.2.25 on 2025-03-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='marketingcampagne',
            name='naam',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='marketingcampagne',
            name='provincie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='marketing.provincie'),
        ),
    ]
