# Generated by Django 3.2.25 on 2025-03-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20250307_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampagne',
            name='uitgegeven_bedrag',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
