# Generated by Django 3.2.25 on 2025-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_marketingcampagne_uitgegeven_bedrag'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampagne',
            name='strategie',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('krant', 'Krant'), ('radio', 'Radio'), ('viavia', 'Viavia'), ('folder', 'Folder'), ('sponsoring', 'Sponsoring'), ('anders', 'Anders')], max_length=50),
        ),
    ]
