# Generated by Django 3.2.25 on 2025-03-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_marketingcampagne_strategie'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampagne',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
