# Generated by Django 5.1.7 on 2025-04-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boekhouding_grootboekrekeningen', '0001_initial'),
        ('marketing', '0005_marketingcampagne_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampagne',
            name='grootboekrekening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boekhouding_grootboekrekeningen.grootboekrekening', verbose_name='Grootboekrekening'),
        ),
    ]
