# Generated by Django 5.1.7 on 2025-04-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klanten', '0005_remove_klantnotitie_dossier_delete_klantdossier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlantDossier',
            fields=[
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('klantnummer', models.AutoField(primary_key=True, serialize=False)),
                ('voornaam', models.CharField(max_length=100)),
                ('achternaam', models.CharField(max_length=100)),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('straat', models.CharField(max_length=200)),
                ('huisnummer', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=10)),
                ('woonplaats', models.CharField(max_length=100)),
                ('telefoonnummer', models.CharField(max_length=20)),
                ('emailadres', models.EmailField(max_length=254)),
                ('zorginstelling', models.CharField(blank=True, help_text='Indien van toepassing', max_length=200, null=True)),
                ('onder_bewind', models.BooleanField(default=False, help_text='Is de klant onder bewind?')),
                ('bewindvoerder_naam', models.CharField(blank=True, max_length=100, null=True)),
                ('bewindvoerder_adres', models.CharField(blank=True, max_length=200, null=True)),
                ('bewindvoerder_telefoon', models.CharField(blank=True, max_length=20, null=True)),
                ('bewindvoerder_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('verzekeringsnummer', models.CharField(max_length=100)),
                ('factuur_geschiedenis', models.JSONField(blank=True, null=True)),
                ('werkbon_geschiedenis', models.JSONField(blank=True, null=True)),
                ('extra_fields', models.JSONField(blank=True, null=True)),
                ('is_overleden', models.BooleanField(default=False, help_text='Markeer dossier als afgesloten bij overlijden')),
                ('overlijdensdatum', models.DateField(blank=True, help_text='Datum van overlijden, indien van toepassing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('klant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='klanten.klant')),
            ],
        ),
        migrations.CreateModel(
            name='KlantNotitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notities', to='klantdossier.klantdossier')),
            ],
        ),
    ]
