# Generated by Django 5.1.7 on 2025-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grootboekrekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Rekeningcode')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam van de rekening')),
                ('omschrijving', models.TextField(blank=True, verbose_name='Omschrijving')),
            ],
            options={
                'verbose_name': 'Grootboekrekening',
                'verbose_name_plural': 'Grootboekrekeningen',
            },
        ),
    ]
