# Generated by Django 3.2.25 on 2025-03-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klanten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlantDossier',
            fields=[
                ('klantnummer', models.AutoField(primary_key=True, serialize=False)),
                ('voornaam', models.CharField(max_length=100)),
                ('achternaam', models.CharField(max_length=100)),
                ('straat', models.CharField(max_length=200)),
                ('huisnummer', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=10)),
                ('woonplaats', models.CharField(max_length=100)),
                ('telefoonnummer', models.CharField(max_length=20)),
                ('emailadres', models.EmailField(max_length=254)),
                ('zorginstelling', models.CharField(help_text='Selecteer uit de lijst (lijsten moeten we nog maken)', max_length=200)),
                ('onder_bewind', models.BooleanField(default=False, help_text='Is de klant onder bewind?')),
                ('bewindvoerder_gegevens', models.JSONField(blank=True, null=True)),
                ('verzekeringsnummer', models.CharField(max_length=100)),
                ('factuur_geschiedenis', models.JSONField(blank=True, null=True)),
                ('werkbon_geschiedenis', models.JSONField(blank=True, null=True)),
                ('extra_fields', models.JSONField(blank=True, help_text='Extra velden toegevoegd door de beheerder', null=True)),
                ('is_overleden', models.BooleanField(default=False, help_text='Markeer dossier als afgesloten bij overlijden')),
                ('overlijdensdatum', models.DateField(blank=True, help_text='Datum van overlijden, indien van toepassing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opdrachtgever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('adres', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('telefoon', models.CharField(blank=True, max_length=20, verbose_name='Telefoonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('kvk', models.CharField(blank=True, max_length=50, verbose_name='KvK-nummer')),
                ('contactpersoon', models.CharField(blank=True, max_length=100, verbose_name='Contactpersoon')),
                ('woonplaats', models.CharField(blank=True, max_length=100, verbose_name='Woonplaats')),
            ],
        ),
        migrations.AddField(
            model_name='klant',
            name='adres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='herkomst',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='mantelzorger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='klant',
            name='mantelzorger_geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='mantelzorger_naam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='mantelzorger_telefoon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='onder_bewind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='klant',
            name='telefoon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='verzekeringsnummer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='woonplaats',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='klant',
            name='naam',
            field=models.CharField(max_length=255),
        ),
    ]
