# Generated by Django 3.2.25 on 2025-03-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klanten', '0002_auto_20250317_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klantdossier',
            name='bewindvoerder_gegevens',
        ),
        migrations.AddField(
            model_name='klantdossier',
            name='bewindvoerder_adres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='klantdossier',
            name='bewindvoerder_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='klantdossier',
            name='bewindvoerder_naam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='klantdossier',
            name='bewindvoerder_telefoon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='klantdossier',
            name='geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klantdossier',
            name='notities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='klantdossier',
            name='extra_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='klantdossier',
            name='zorginstelling',
            field=models.CharField(blank=True, help_text='Indien van toepassing', max_length=200, null=True),
        ),
    ]
