# Generated by Django 3.2.25 on 2025-03-17 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klanten', '0003_auto_20250317_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klantdossier',
            name='notities',
        ),
        migrations.CreateModel(
            name='KlantNotitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notities', to='klanten.klantdossier')),
            ],
        ),
    ]
