# Generated by Django 5.1.7 on 2025-03-31 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klanten', '0004_auto_20250317_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klantnotitie',
            name='dossier',
        ),
        migrations.DeleteModel(
            name='KlantDossier',
        ),
        migrations.DeleteModel(
            name='KlantNotitie',
        ),
    ]
