# Generated by Django 5.1.7 on 2025-03-24 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0005_marketingcampagne_archived'),
        ('tarieven', '0005_alter_nzacode_beschrijving'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('adres', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('woonplaats', models.CharField(blank=True, max_length=100, verbose_name='Woonplaats')),
                ('geboortedatum', models.DateField(blank=True, null=True, verbose_name='Geboortedatum')),
                ('telefoon', models.CharField(blank=True, max_length=20, verbose_name='Telefoonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('verzekeringsnummer', models.CharField(blank=True, max_length=50, verbose_name='Verzekeringsnummer')),
            ],
        ),
        migrations.CreateModel(
            name='Opdrachtgever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('adres', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('telefoon', models.CharField(blank=True, max_length=20, verbose_name='Telefoonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('kvk', models.CharField(blank=True, max_length=50, verbose_name='KvK-nummer')),
                ('contactpersoon', models.CharField(blank=True, max_length=100, verbose_name='Contactpersoon')),
                ('woonplaats', models.CharField(blank=True, max_length=100, verbose_name='Woonplaats')),
            ],
        ),
        migrations.CreateModel(
            name='Werkbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('werkbonnummer', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Werkbonnummer')),
                ('barcode', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Barcode')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('gebitsdatum', models.DateField(blank=True, null=True, verbose_name='Gebitsdatum')),
                ('tandkleur', models.CharField(blank=True, choices=[('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3'), ('a3,5', 'A3,5'), ('c1', 'C1'), ('c2', 'C2')], max_length=10, verbose_name='Tandkleur')),
                ('aanmaakdatum', models.DateField(auto_now_add=True, verbose_name='Aanmaakdatum')),
                ('aanvang_werkzaamheden', models.DateTimeField(blank=True, null=True, verbose_name='Aanvang werkzaamheden')),
                ('naaminpersen', models.BooleanField(default=False, verbose_name='Naaminpersen?')),
                ('behandelaar', models.CharField(blank=True, choices=[('Jellie', 'Jellie'), ('Romy', 'Romy'), ('Sabrina', 'Sabrina'), ('Ellen', 'Ellen'), ('Usman', 'Usman')], max_length=100, verbose_name='Behandelaar')),
                ('technicus', models.CharField(blank=True, choices=[('Job', 'Job'), ('Myrthe', 'Myrthe'), ('Jellie', 'Jellie'), ('Sabrina', 'Sabrina'), ('Romy', 'Romy'), ('Ellen', 'Ellen'), ('Usman', 'Usman')], max_length=100, verbose_name='Technicus')),
                ('notities', models.TextField(blank=True, verbose_name='Notities')),
                ('facturabel_garantie', models.CharField(blank=True, choices=[('facturabel', 'Facturabel'), ('garantie', 'Garantie')], max_length=20, verbose_name='Facturabel of Garantie')),
                ('verkoopwaarde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inkoopwaarde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_behandeling', 'In behandeling'), ('gesloten', 'Gesloten')], default='open', max_length=20, verbose_name='Status')),
                ('klant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werkbonnen', to='planning.klant')),
                ('marketing_optie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.marketingcampagne')),
                ('nza_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarieven.nzacode', verbose_name='NZA Code')),
                ('opdrachtgever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werkbonnen', to='planning.opdrachtgever')),
            ],
        ),
        migrations.CreateModel(
            name='WerkUurLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_tijd', models.DateTimeField(verbose_name='Start Tijd')),
                ('eind_tijd', models.DateTimeField(blank=True, null=True, verbose_name='Eind Tijd')),
                ('werkbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uur_logs', to='planning.werkbon')),
                ('werknemer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
