# Generated by Django 3.2.25 on 2025-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Werkbon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('werkbonnummer', models.CharField(max_length=20, unique=True, verbose_name='Werkbonnummer')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Barcode')),
                ('klant_naam', models.CharField(max_length=100, verbose_name='Klantnaam')),
                ('klant_adres', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('klant_woonplaats', models.CharField(blank=True, max_length=100, verbose_name='Woonplaats')),
                ('klant_geboortedatum', models.DateField(blank=True, null=True, verbose_name='Geboortedatum')),
                ('klant_telefoon', models.CharField(blank=True, max_length=20, verbose_name='Telefoonnummer')),
                ('klant_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('klant_verzekeringsnummer', models.CharField(blank=True, max_length=50, verbose_name='Verzekeringsnummer')),
                ('mantelzorger', models.BooleanField(default=False, verbose_name='Heeft mantelzorger?')),
                ('onder_bewind', models.BooleanField(default=False, verbose_name='Onder bewind?')),
                ('klant_herkomst', models.CharField(blank=True, max_length=100, verbose_name='Hoe is de klant bij ons gekomen?')),
                ('opdrachtgever_naam', models.CharField(blank=True, max_length=100, verbose_name='Opdrachtgevernaam')),
                ('opdrachtgever_adres', models.CharField(blank=True, max_length=200, verbose_name='Opdrachtgever adres')),
                ('opdrachtgever_telefoon', models.CharField(blank=True, max_length=20, verbose_name='Opdrachtgever telefoon')),
                ('opdrachtgever_email', models.EmailField(blank=True, max_length=254, verbose_name='Opdrachtgever email')),
                ('opdrachtgever_kvk', models.CharField(blank=True, max_length=50, verbose_name='KvK-nummer')),
                ('opdrachtgever_contactpersoon', models.CharField(blank=True, max_length=100, verbose_name='Contactpersoon')),
                ('opdrachtgever_woonplaats', models.CharField(blank=True, max_length=100, verbose_name='Opdrachtgever woonplaats')),
                ('leeftijd_gebitsstatus', models.CharField(blank=True, max_length=50, verbose_name='Leeftijd gebit')),
                ('tandkleur', models.CharField(blank=True, max_length=50, verbose_name='Tandkleur')),
                ('aanvang_werkzaamheden', models.DateField(blank=True, null=True, verbose_name='Aanvang werkzaamheden')),
                ('naaminpersen', models.BooleanField(default=False, verbose_name='Naaminpersen?')),
                ('behandelaar', models.CharField(blank=True, max_length=100, verbose_name='Behandelaar')),
                ('technicus', models.CharField(blank=True, max_length=100, verbose_name='Technicus')),
                ('notities', models.TextField(blank=True, verbose_name='Notities')),
            ],
        ),
    ]
