# Generated by Django 5.1.7 on 2025-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werkbon',
            name='aanvang_werkzaamheden',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aanvang werkzaamheden'),
        ),
    ]
