# Generated by Django 3.2.25 on 2025-02-27 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0002_alter_werkbon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('adres', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('woonplaats', models.CharField(blank=True, max_length=100, verbose_name='Woonplaats')),
                ('geboortedatum', models.DateField(blank=True, null=True, verbose_name='Geboortedatum')),
                ('telefoon', models.CharField(blank=True, max_length=20, verbose_name='Telefoonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('verzekeringsnummer', models.CharField(blank=True, max_length=50, verbose_name='Verzekeringsnummer')),
                ('mantelzorger', models.BooleanField(default=False, verbose_name='Heeft mantelzorger?')),
                ('onder_bewind', models.BooleanField(default=False, verbose_name='Onder bewind?')),
                ('herkomst', models.CharField(blank=True, max_length=100, verbose_name='Hoe is de klant bij ons gekomen?')),
            ],
        ),
        migrations.CreateModel(
            name='Opdrachtgever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('adres', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('telefoon', models.CharField(blank=True, max_length=20, verbose_name='Telefoonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('kvk', models.CharField(blank=True, max_length=50, verbose_name='KvK-nummer')),
                ('contactpersoon', models.CharField(blank=True, max_length=100, verbose_name='Contactpersoon')),
                ('woonplaats', models.CharField(blank=True, max_length=100, verbose_name='Woonplaats')),
            ],
        ),
        migrations.RenameField(
            model_name='werkbon',
            old_name='leeftijd_gebitsstatus',
            new_name='leeftijd_gebit',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='klant_adres',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='klant_email',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='klant_geboortedatum',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='klant_herkomst',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='klant_naam',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='klant_telefoon',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='klant_verzekeringsnummer',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='klant_woonplaats',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='mantelzorger',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='onder_bewind',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='opdrachtgever_adres',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='opdrachtgever_contactpersoon',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='opdrachtgever_email',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='opdrachtgever_kvk',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='opdrachtgever_naam',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='opdrachtgever_telefoon',
        ),
        migrations.RemoveField(
            model_name='werkbon',
            name='opdrachtgever_woonplaats',
        ),
        migrations.AddField(
            model_name='werkbon',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_behandeling', 'In behandeling'), ('gesloten', 'Gesloten')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='WerkUurLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_tijd', models.DateTimeField(verbose_name='Start Tijd')),
                ('eind_tijd', models.DateTimeField(blank=True, null=True, verbose_name='Eind Tijd')),
                ('werkbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uur_logs', to='planning.werkbon')),
                ('werknemer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='werkbon',
            name='klant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werkbonnen', to='planning.klant'),
        ),
        migrations.AddField(
            model_name='werkbon',
            name='opdrachtgever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werkbonnen', to='planning.opdrachtgever'),
        ),
    ]
