# Generated by Django 3.2.25 on 2025-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20250227_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werkbon',
            name='behandelaar',
            field=models.CharField(blank=True, choices=[('Jellie', 'Jellie'), ('Romy', 'Romy'), ('Sabrina', 'Sabrina'), ('Ellen', 'Ellen'), ('Usman', 'Usman')], max_length=100, verbose_name='Behandelaar'),
        ),
        migrations.AlterField(
            model_name='werkbon',
            name='technicus',
            field=models.CharField(blank=True, choices=[('Job', 'Job'), ('Myrthe', 'Myrthe'), ('Jellie', 'Jellie'), ('Sabrina', 'Sabrina'), ('Romy', 'Romy'), ('Ellen', 'Ellen'), ('Usman', 'Usman')], max_length=100, verbose_name='Technicus'),
        ),
    ]
