# Generated by Django 3.2.25 on 2025-02-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20250227_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werkbon',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='werkbon',
            name='werkbonnummer',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Werkbonnummer'),
        ),
    ]
