# Generated by Django 3.2.25 on 2025-02-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_auto_20250227_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='werkbon',
            name='leeftijd_gebit',
        ),
        migrations.AddField(
            model_name='werkbon',
            name='facturabel_garantie',
            field=models.CharField(blank=True, choices=[('facturabel', 'Facturabel'), ('garantie', 'Garantie')], max_length=20, verbose_name='Facturabel of Garantie'),
        ),
        migrations.AddField(
            model_name='werkbon',
            name='gebitsdatum',
            field=models.DateField(blank=True, null=True, verbose_name='Gebitsdatum'),
        ),
        migrations.AddField(
            model_name='werkbon',
            name='klant_herkomst',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('krant', 'Krant'), ('radio', 'Radio'), ('viavia', 'Viavia'), ('folder', 'Folder'), ('sponsoring', 'Sponsoring'), ('anders', 'Anders')], max_length=20, verbose_name='Hoe is de klant bij ons gekomen?'),
        ),
        migrations.AddField(
            model_name='werkbon',
            name='nza_code',
            field=models.CharField(blank=True, choices=[('code1', 'Code 1'), ('code2', 'Code 2'), ('code3', 'Code 3')], max_length=20, verbose_name='NZA Code'),
        ),
        migrations.AlterField(
            model_name='werkbon',
            name='tandkleur',
            field=models.CharField(blank=True, choices=[('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3'), ('a3,5', 'A3,5'), ('c1', 'C1'), ('c2', 'C2')], max_length=10, verbose_name='Tandkleur'),
        ),
    ]
