# Generated by Django 3.2.25 on 2025-02-27 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_auto_20250227_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='werkbon',
            name='klant_herkomst',
        ),
        migrations.AddField(
            model_name='klant',
            name='mantelzorger_geboortedatum',
            field=models.DateField(blank=True, null=True, verbose_name='Mantelzorger Geboortedatum'),
        ),
        migrations.AddField(
            model_name='klant',
            name='mantelzorger_naam',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mantelzorger Naam'),
        ),
        migrations.AddField(
            model_name='klant',
            name='mantelzorger_telefoon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mantelzorger Telefoon'),
        ),
        migrations.AddField(
            model_name='werkbon',
            name='aanmaakdatum',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Aanmaakdatum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='klant',
            name='herkomst',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('krant', 'Krant'), ('radio', 'Radio'), ('viavia', 'Viavia'), ('folder', 'Folder'), ('sponsoring', 'Sponsoring'), ('anders', 'Anders')], max_length=20, verbose_name='Hoe is de klant bij ons gekomen?'),
        ),
    ]
