# Generated by Django 3.2.25 on 2025-03-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_marketingcampagne_uitgegeven_bedrag'),
        ('planning', '0007_auto_20250227_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='werkbon',
            name='inkoopwaarde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='werkbon',
            name='marketing_optie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.marketingcampagne'),
        ),
        migrations.AddField(
            model_name='werkbon',
            name='verkoopwaarde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
