# Generated by Django 3.2.25 on 2025-03-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarieven', '0004_auto_20250307_1705'),
        ('planning', '0008_auto_20250307_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werkbon',
            name='nza_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarieven.nzacode', verbose_name='NZA Code'),
        ),
    ]
