# Generated by Django 3.2.25 on 2025-03-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_update_invalid_nza_codes'),
    ]

    operations = [
    ]
