# Generated by Django 3.2.25 on 2025-03-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_fix_invalid_nza_codes'),
        ('planning', '0012_fix_invalid_nza_codes'),
    ]

    operations = [
    ]
