# Generated by Django 5.1.7 on 2025-04-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factuur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=100)),
                ('omschrijving', models.TextField(blank=True)),
                ('datum', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
