# Generated by Django 5.1.7 on 2025-04-11 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crediteuren', '0002_crediteur_adres_crediteur_betaalvoorwaarden_and_more'),
        ('debiteuren', '0002_debiteur_adres_debiteur_betaalvoorwaarden_and_more'),
        ('facturatie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factuur',
            name='nummer',
        ),
        migrations.RemoveField(
            model_name='factuur',
            name='omschrijving',
        ),
        migrations.AddField(
            model_name='factuur',
            name='bedrag_excl_btw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factuur',
            name='btw_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factuur',
            name='crediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crediteuren.crediteur'),
        ),
        migrations.AddField(
            model_name='factuur',
            name='debiteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='debiteuren.debiteur'),
        ),
        migrations.AddField(
            model_name='factuur',
            name='factuur_type',
            field=models.CharField(choices=[('verkoop', 'Verkoopfactuur'), ('inkoop', 'Inkoopfactuur')], default='onbekend', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factuur',
            name='factuurnummer',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factuur',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('betaald', 'Betaald'), ('vervallen', 'Vervallen')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='factuur',
            name='totaal_bedrag',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factuur',
            name='datum',
            field=models.DateField(),
        ),
    ]
