# Generated by Django 5.1.7 on 2025-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Werkbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('werkbonnummer', models.CharField(max_length=20, unique=True, verbose_name='Werkbonnummer')),
                ('klant', models.CharField(max_length=100, verbose_name='Klant')),
                ('behandelaar', models.CharField(max_length=100, verbose_name='Behandelaar')),
                ('honorarium', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Honorarium')),
                ('inkoopwaarde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Inkoopwaarde')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('aanmaakdatum', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
