# Generated by Django 5.1.7 on 2025-04-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunstgebitaanhuis', '0001_initial'),
        ('tarieven', '0008_nzacode_grootboekrekening'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='werkbon',
            options={'verbose_name': 'Werkbon', 'verbose_name_plural': 'Werkbonnen'},
        ),
        migrations.AddField(
            model_name='werkbon',
            name='facturabel_garantie',
            field=models.CharField(choices=[('facturabel', 'Facturabel'), ('garantie', 'Garantie')], default='onbekend', max_length=20, verbose_name='Facturering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='werkbon',
            name='nza_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werkbon_kunstgebitaanhuis', to='tarieven.nzacode'),
        ),
    ]
