# Generated by Django 5.1.7 on 2025-04-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunstgebitaanhuis', '0002_alter_werkbon_options_werkbon_facturabel_garantie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='werkbon',
            name='honorarium',
        ),
        migrations.AddField(
            model_name='werkbon',
            name='verkoopwaarde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Verkoopwaarde'),
        ),
    ]
