# Generated by Django 5.1.7 on 2025-04-11 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarieven', '0008_nzacode_grootboekrekening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Werkbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('werkbonnummer', models.CharField(max_length=20, unique=True, verbose_name='Werkbonnummer')),
                ('klant', models.CharField(max_length=100, verbose_name='Klant')),
                ('technicus', models.CharField(max_length=100, verbose_name='Technicus')),
                ('facturabel_garantie', models.CharField(max_length=20, verbose_name='Facturabel of Garantie')),
                ('omzet', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Omzet')),
                ('nza_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werkbon_laboratorium', to='tarieven.nzacode')),
            ],
            options={
                'verbose_name': 'Werkbon',
                'verbose_name_plural': 'Werkbonnen',
            },
        ),
    ]
