# Generated by Django 5.1.7 on 2025-04-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('omschrijving', models.TextField(blank=True)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
