# Generated by Django 5.1.7 on 2025-04-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boekhouding_grootboekrekeningen', '0001_initial'),
        ('debiteuren', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debiteur',
            name='adres',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='debiteur',
            name='betaalvoorwaarden',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='debiteur',
            name='bic',
            field=models.CharField(blank=True, help_text='BIC', max_length=11),
        ),
        migrations.AddField(
            model_name='debiteur',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='debiteur',
            name='grootboekrekening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boekhouding_grootboekrekeningen.grootboekrekening', verbose_name='Grootboekrekening'),
        ),
        migrations.AddField(
            model_name='debiteur',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN', max_length=34),
        ),
        migrations.AddField(
            model_name='debiteur',
            name='telefoonnummer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
