# Generated by Django 3.2.25 on 2025-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('beschrijving', models.TextField(blank=True)),
                ('bedrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actief', models.BooleanField(default=True)),
            ],
        ),
    ]
