# Generated by Django 3.2.25 on 2025-03-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarieven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NZACode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='NZA Code')),
                ('techniekkosten', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Techniekkosten')),
                ('honorarium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Honorarium')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
            ],
        ),
        migrations.DeleteModel(
            name='Tarief',
        ),
    ]
