# Generated by Django 3.2.25 on 2025-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarieven', '0002_auto_20250307_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='nzacode',
            name='aantal_werkfases',
            field=models.PositiveIntegerField(default=0, verbose_name='Aantal Werkfases'),
        ),
        migrations.AddField(
            model_name='nzacode',
            name='tijdsduur_per_fase',
            field=models.DurationField(blank=True, null=True, verbose_name='Tijdsduur per Fase'),
        ),
    ]
