# Generated by Django 3.2.25 on 2025-03-07 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarieven', '0003_auto_20250307_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nzacode',
            name='aantal_werkfases',
        ),
        migrations.RemoveField(
            model_name='nzacode',
            name='tijdsduur_per_fase',
        ),
        migrations.CreateModel(
            name='Werkfase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgorde', models.PositiveIntegerField(default=1, verbose_name='Fase Volgorde')),
                ('duur', models.DurationField(blank=True, null=True, verbose_name='Tijdsduur')),
                ('nza_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='werkfases', to='tarieven.nzacode')),
            ],
        ),
    ]
