# Generated by Django 3.2.25 on 2025-03-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarieven', '0004_auto_20250307_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nzacode',
            name='beschrijving',
            field=models.CharField(blank=True, max_length=60, verbose_name='Beschrijving'),
        ),
    ]
