# Generated by Django 5.1.7 on 2025-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarieven', '0005_alter_nzacode_beschrijving'),
    ]

    operations = [
        migrations.AddField(
            model_name='werkfase',
            name='naam',
            field=models.CharField(default='Standaard Fase', help_text='Geef een duidelijke naam voor deze werkfase', max_length=100, verbose_name='Werkfase Naam'),
        ),
    ]
