# Generated by Django 5.1.7 on 2025-04-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarieven', '0006_werkfase_naam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werkfase',
            name='naam',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fase Naam'),
        ),
    ]
