# Generated by Django 5.1.7 on 2025-04-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boekhouding_grootboekrekeningen', '0001_initial'),
        ('tarieven', '0007_alter_werkfase_naam'),
    ]

    operations = [
        migrations.AddField(
            model_name='nzacode',
            name='grootboekrekening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boekhouding_grootboekrekeningen.grootboekrekening', verbose_name='Grootboekrekening'),
        ),
    ]
